using JetBrains.Annotations;
using System;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UI;

public class TestGameManager : MonoBehaviour
{
    public const int NO_MONEY_ELIMINATED = 0;
    public static TestGameManager Instance = null;//НЬБлХц ЦаХЯ

    public enum GameState
    {
        start,
        deal,
        afterDeal,
        bet,
        afterBet,
        end
    };

    [Header("Game State")]
    [SerializeField] public GameState gameState;
    //Card UI
    [Header("Card UI")]
    [SerializeField] private Text[] playerCard0Text;
    [SerializeField] private Text[] playerCard1Text;
    [SerializeField] private Text[] playerCard2Text;
    [SerializeField] private Text[] playerSumText;
    [SerializeField] private Text TopCardText;
    [SerializeField] private Text BottomCardText;

    //Card Value
    [Header("Card Value")]
    //public string[] playerName;
    //[SerializeField] private int[] playerCardNum;
    [SerializeField] private int[] playerCard0Num;
    [SerializeField] private int[] playerCard1Num;
    [SerializeField] private int[] playerCard2Num;
    [SerializeField] public int[] playerCardSum;

    [SerializeField] public bool[] playerIsCheat = new bool[4] { false, false, false, false };
    [SerializeField] private List<int> CardDeck = null;

    [Header("In Game Counts")]
    [SerializeField] public int foldPlayerCnt = 0;
    [SerializeField] public int IngamePlayerCnt = 4;

    [Header("Turn Info")]
    [SerializeField] private int gameTurn = 0;
    //[SerializeField] private int dealtCardCount = 0; // ФЋЕх ГЊДВСжДТ ХЯ
    [SerializeField] private int dealOrder = 0; // ЧіРч ФЋЕх ГЊДВСй ЧУЗЙРЬОю МјМ­

    [Header("etc")]
    [SerializeField] private GameObject[] Player;
    [SerializeField] private List<PlayerData> playerDataSet = null;
    [SerializeField] public Player[] playerArray = null;
    
    [SerializeField] public TestBettingManager betMan;
    [SerializeField] private IEnumerator[] cheatCoroutine = new IEnumerator[4];

    private void Awake()
    {
        if (null == Instance) //Е№РкРЮЦаХЯСп НЬБлХц ЦаХЯ
        {
            Instance = this;
            DontDestroyOnLoad(this.gameObject);
        }
        else
        {
            //Destroy(this.gameObject);
        }
    }

    void Start()
    {
        InitPlayer();
        IngamePlayerCnt = 4;
        SetStateStart();
    }

    public void Update()
    {

    }

    #region set state

    public void SetStateStart()
    {
        gameState = GameState.start;
        CardDeck = InitDeck();
        CardDeck = shuffleDeck(CardDeck);
        TopCardText.text = CardDeck[0].ToString();
        BottomCardText.text = CardDeck[CardDeck.Count - 1].ToString();
        for (int i = 0; i < playerArray.Length; i++) //РдРх КЃЦУ
        {
            betMan.entranceBet(i);
        }
        betMan.UpdateUIText();
        SetStateDeal();
    }

    public void SetStateDeal()
    {
        gameState = GameState.deal;
        dealOrder = 0;
        BottomCardText.text = CardDeck[CardDeck.Count - 1].ToString();
    }

    public void SetStateAfterDeal()
    {
        gameState = GameState.afterDeal;
        SetStateBet();
    }

    public void SetStateBet()
    {
        gameState = GameState.bet;
        betMan.TriggerBetting();
    }

    public void SetStateAfterBet()
    {
        gameState = GameState.afterBet;
        IsBetOver();
    }

    public void SetStateEnd()
    {
        gameState = GameState.end;
        ShowCardSum();
        if (foldPlayerCnt == IngamePlayerCnt - 1)
        {
            for (int i = 0; i < betMan.isFold.Length; i++)
            {
                if (betMan.isFold[i] == false)
                {
                    betMan.CalculateResult(betMan.DecideWinnerByFold(i));
                    return;
                }
            }
        }
        else
        {
            betMan.CalculateResult(betMan.DecideWinner(playerCardSum));
        }
        betMan.isBetOver = false;
        //SetStateStart();
    }

    #endregion


    #region start

    private List<int> InitDeck()
    {
        int temp;
        List<int> initDeck = new List<int>();

        for (int i = 0; i < 52; i++) //ФЋЕх Л§МК
        {
            temp = i % 13 + 1;
            temp = temp > 10 ? 10 : temp;
            initDeck.Add(temp);
        }

        return initDeck;
    }

    private void InitPlayer()
    {
        for (int i = 0; i < 4; i++)
        {
            int temp = UnityEngine.Random.Range(0, playerDataSet.Count);
            playerArray[i].playerData = playerDataSet[temp];
            playerArray[i].initData();
            playerDataSet.RemoveAt(temp);
        }
    }

    private List<int> shuffleDeck(List<int> deck)
    {
        int random1, random2;
        int temp;
        for (int i = 0; i < deck.Count; ++i)
        {
            random1 = UnityEngine.Random.Range(0, deck.Count);
            random2 = UnityEngine.Random.Range(0, deck.Count);

            temp = deck[random1];
            deck[random1] = deck[random2];
            deck[random2] = temp;
        }
        return deck;
    }

    #endregion


    #region deal

    public void CheckDealOrder()
    {
        if (gameState != GameState.deal)
        {
            return;
        }
        while (true)
        {
            //if (betMan.isFold.Length > dealOrder)
            if (betMan.isFold[dealOrder])
            {
                ++dealOrder;
                IsDealOver();
            }
            else
            {
                return;
            }
        }
    }

    public void IsDealOver()
    {
        if (dealOrder >= betMan.isFold.Length)
        {
            SetStateAfterDeal();
            return;
        }
        if (betMan.isFold[dealOrder] == true)
        {
            ++dealOrder;
            IsDealOver();
        }
    }

    

    public void NormalDeal()
    {
        CheckDealOrder();

        if (gameState != GameState.deal)
        {
            return;
        }

        switch (betMan.dealtCardCount)
        {
            case 0:
                playerCard0Num[dealOrder] = CardDeck[0];
                playerCardSum[dealOrder] += playerCard0Num[dealOrder];
                playerCard0Text[dealOrder].text = playerCard0Num[dealOrder].ToString();
                break;
            case 1:
                playerCard1Num[dealOrder] = CardDeck[0];
                playerCardSum[dealOrder] += playerCard1Num[dealOrder];
                playerCard1Text[dealOrder].text = playerCard1Num[dealOrder].ToString();
                break;
            case 2:
                playerCard2Num[dealOrder] = CardDeck[0];
                playerCardSum[dealOrder] += playerCard2Num[dealOrder];
                playerCard2Text[dealOrder].text = playerCard2Num[dealOrder].ToString();
                
                cheatCoroutine[dealOrder] = CheatCycle(dealOrder);
                StartCoroutine(cheatCoroutine[dealOrder]);

                break;
            default:
                break;
        }
        CardDeck.Remove(CardDeck[0]);
        TopCardText.text = CardDeck[0].ToString();
        dealOrder++;
        IsDealOver();


    }

    public void BottomDeal()
    {
        CheckDealOrder();

        if (gameState != GameState.deal)
        {
            return;
        }

        switch (betMan.dealtCardCount)
        {
            case 0:
                playerCard0Num[dealOrder] = CardDeck[CardDeck.Count - 1];
                playerCardSum[dealOrder] += playerCard0Num[dealOrder];
                playerCard0Text[dealOrder].text = playerCard0Num[dealOrder].ToString();
                break;
            case 1:
                playerCard1Num[dealOrder] = CardDeck[CardDeck.Count - 1];
                playerCardSum[dealOrder] += playerCard1Num[dealOrder];
                playerCard1Text[dealOrder].text = playerCard1Num[dealOrder].ToString();
                break;
            case 2:
                playerCard2Num[dealOrder] = CardDeck[CardDeck.Count - 1];
                playerCardSum[dealOrder] += playerCard2Num[dealOrder];
                playerCard2Text[dealOrder].text = playerCard2Num[dealOrder].ToString();
                cheatCoroutine[dealOrder] = CheatCycle(dealOrder);
                StartCoroutine(cheatCoroutine[dealOrder]);
                break;

        }
        CardDeck.RemoveAt(CardDeck.Count - 1);
        BottomCardText.text = "Unknown";
        dealOrder++;
        IsDealOver();
    }

    #endregion


    #region afterDeal

    private void GlimpseBottomCard() 
    {
        //УпШФ АГЙп
    }

    #endregion


    #region afterBet

    private void IsBetOver()
    {
        if (betMan.dealtCardCount == 3 || foldPlayerCnt == IngamePlayerCnt - 1)
        {
            SetStateEnd();
        }
        else
        {
            SetStateDeal();
        }
    }

    #endregion


    #region end

    private void ShowCardSum()
    {
        for (int i = 0; i < 4; i++)
            playerSumText[i].text = playerCardSum[i].ToString();
    }

    private void ResetDealtCard()
    {
        Array.Clear(playerCard0Num, 0, playerCard0Num.Length);
        Array.Clear(playerCard1Num, 0, playerCard1Num.Length);
        Array.Clear(playerCard2Num, 0, playerCard2Num.Length);
        Array.Clear(playerCardSum, 0, playerCardSum.Length);
        dealOrder = 0;
        foldPlayerCnt = 0;
        for (int i = 0; i < 4; i++)
        {
            playerCard0Text[i].text = " - ";
            playerCard1Text[i].text = " - ";
            playerCard2Text[i].text = " - ";
            playerSumText[i].text = "Sum";
        }
    }

    public void EliminatePlayer(int idx, int type) //0РЬИщ КЃЦУБн КЮСЗ, 1РЬИщ АэЙп
    {
        switch (type)
        {
            case NO_MONEY_ELIMINATED:

                break;

            default:
                Debug.Log("-");
                break;
        }
        IngamePlayerCnt--;


        //idx ЧУЗЙРЬОю СІАХУГИЎ
    }

    private IEnumerator NextTurn()
    {
        yield return new WaitForSeconds(5f);
        gameTurn++;
        ResetDealtCard();
        betMan.ResetBet();
        SetStateStart();
    }

    public void TriggerNextTurn()
    {
        StartCoroutine(NextTurn());
    }

    public void GameOver()
    {
        Debug.Log("АдРг ГЁ!");
    }

    #endregion


    private IEnumerator CheatCycle(int playerIdx) //ФкЗчЦО
    {

        while (true)
        {
            DecideToSwitch(playerIdx);
            yield return new WaitForSeconds(UnityEngine.Random.Range(10, 30));
        }
    }
    // 1Йј ЧУЗЙРЬОю ЙоОвРЛЖЇ НЧЧр(1ЙјРИЗЮ)
    // 2Йј ЧУЗЙРЬОю ЙоОвРЛЖЇ НЧЧр(2ЙјРИЗЮ)
    // ,...
    // 4Йј ЧУЗЙРЬЄУ~~

    


    #region Cheat
    public void DecideToSwitch(int idx)
    {
        if (playerIsCheat[idx] == true)
        {
            SwitchCard(idx);
        }


        if (playerCardSum[idx] > 21)
        {

            if (20f + playerArray[idx].cheatFrequency < UnityEngine.Random.Range(0, 101))
            
            {
                SwitchCard(idx);
                StopCoroutine(cheatCoroutine[idx]);

            }


        }
    }
    public void SwitchCard(int idx)
    {
        //ЛчБтФЁДТ ОжДЯИоРЬМЧ РчЛ§
        Debug.Log("CHEAT! " + idx);
        playerArray[idx].Start_DoCheat();
        playerCard0Num[idx] = 5;
        playerCard1Num[idx] = 6;
        playerCard2Num[idx] = 10; //МћБф ФЋЕх 3РхРЛ АЁСіАэ ЦЏСЄ Ию РхИИ ЙйВйДТ НФРИЗЮ СЖРлЧЯЕЕЗЯ МіСЄ
        playerCardSum[idx] = 21;


        playerCard0Text[idx].text = playerCard0Num[idx].ToString();
        playerCard1Text[idx].text = playerCard1Num[idx].ToString();
        playerCard2Text[idx].text = playerCard2Num[idx].ToString();

    }
    #endregion

    public void DoCheatCycle()
    {
        cheatCoroutine[dealOrder] = CheatCycle(dealOrder);
        StartCoroutine(cheatCoroutine[dealOrder]);
    }

    //- > ГЛАЁ ЙоРК СїШФКЮХЭ РкБтАЁ ГЛАЁ КЃЦУЧЯБт СїРќ(АГЙп ЦэРЧИІ РЇЧи..) БюСі ФЁЦУ АЁДЩМК РжРН
 

}
