using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class TestBettingManager : MonoBehaviour
{
    [SerializeField] private Player[] playerArray = null;
    [SerializeField] private int[] playerCardSum = null;

    [Header("UI")]
    [SerializeField] private Text[] playerBetText = null;
    [SerializeField] private Text potText = null;
    [SerializeField] private Text[] winnerText = null;
    [SerializeField] private Text[] playerFoldText = null;
    [SerializeField] private Text[] playerSeedText = null;

    [Header("Betting Amount")]
    [SerializeField] private int ante = 10; //ТќПЉБн
    [SerializeField] private int defaultBet = 10; //БтКЛ КЃЦУ ДмРЇ
    [SerializeField] private int roundBet = 0; //ЧиДч КЃЦУ ЦфРЬСюРЧ КЃЦУ ДмРЇ
    [SerializeField] private int maxBet = 10; //ЖѓПюЕх УжДы КЃЦУ БнОз
    [SerializeField] private int pot = 0; //ЦЧЕЗ
    [SerializeField] private int prize = 0; //ЖѓПюЕх ЛѓБн
    [SerializeField] private int eliminationCriteria = 0; //МвРЏБнРЬ ПЉБтБюСі СйОюЕщИщ ЧиДч ЧУЗЙРЬОюАЁ ХзРЬКэРЛ ЖАГВ

    [Header("In Game Data")]
    [SerializeField] private List<int> winner = null;
    [SerializeField] public int dealtCardCount = 0;
    [SerializeField] private int endOrder = 0;
    [SerializeField] public bool[] isFold = null;
    [SerializeField] public bool isBetOver = false;

    void Start()
    {
        playerArray = TestGameManager.Instance.playerArray;
        playerCardSum = TestGameManager.Instance.playerCardSum;
        roundBet = defaultBet;
    }

    //КЃЦУ ЦфРЬСю РќЙн АќИЎ
    //1. КЃЦУ АќИЎ
    //2. Winner By Fold ЛѓНУ УМХЉ

    /*
    public void CheckWinnerByFold()
    {
        if (foldPlayerCnt == IngamePlayerCnt-1)
        {
            for (int j = 0; j < betMan.isFold.Length; j++)
            {
                if (betMan.isFold[j] == false)
                {
                    betMan.CalculateResult(betMan.DecideWinnerByFold(j));
                }
            }
        }
    }
    */
    //3. КЃЦУ ЦфРЬСю СОЗс ШФ gameState afterBetРИЗЮ КЏАц
    //4. ЕЗ СЄЛъБюСі ОъАЁ ЧЯРк

    void Update()
    {
        if (isBetOver)
        {
            StopCoroutine("Betting");
            UpdateUIText();
        }
    }

    public void UpdateUIText()
    {
        for (int i = 0; i < playerArray.Length; i++)
        {
            playerSeedText[i].text = playerArray[i].playerMoney.ToString();
            playerBetText[i].text = playerArray[i].playerBettingMoney.ToString();
            playerFoldText[i].text = isFold[i] ? "FOLD" : "IN";
            potText.text = pot.ToString();
        }
    }

    public void TriggerBetting()
    {
        StartCoroutine(Betting());
    }

    public IEnumerator Betting()
    {
        if(TestGameManager.Instance.gameState != TestGameManager.GameState.bet || isBetOver == true)
        {
            yield break;
        }
        ++dealtCardCount;
        endOrder = playerArray.Length;
        for (int i = 0; i != endOrder && !isBetOver; i = (i+1)%4) //Чб ХЯРЬ ЕЙ ЖЇИЖДй КЃЦУ СјЧр
        {
            yield return new WaitForSeconds(1);
            bet(i);
            playerSeedText[i].text = playerArray[i].playerMoney.ToString();
        }
        yield return new WaitForSeconds(1);
        TestGameManager.Instance.SetStateAfterBet();
    }

    #region betting options
    public void entranceBet(int playerIdx)
    {
        maxBet = ante;
        playerArray[playerIdx].playerBettingMoney += ante;
        playerArray[playerIdx].playerMoney -= ante;
        pot += ante;
        UpdateUIText();
    }

    public void bet(int playerIdx)
    {
        if (isBetOver)
            return;

        if (isFold[playerIdx] == true)
            return;

        if (dealtCardCount == 2
            && (playerCardSum[playerIdx] < 8 || 16 < playerCardSum[playerIdx]))
        {
            fold(playerIdx);


            return;
        }
        else if (dealtCardCount == 3)
        {
            if (playerCardSum[playerIdx] < 17 || 21 < playerCardSum[playerIdx])
            {
                fold(playerIdx);
                return;
            }
            if ((playerCardSum[playerIdx] == 21) && (defaultBet == roundBet))
            {
                raise(playerIdx);
                return;
            }
        }
        call(playerIdx);
    }

    public void call(int playerIdx)
    {
        if (playerArray[playerIdx].playerBettingMoney == maxBet)
        {
            playerArray[playerIdx].playerBettingMoney += roundBet;
            playerArray[playerIdx].playerMoney -= roundBet;
            pot += roundBet;
            maxBet += roundBet;
            endOrder = playerIdx;
        }
        else
        {
            playerArray[playerIdx].playerMoney += playerArray[playerIdx].playerBettingMoney;
            pot -= playerArray[playerIdx].playerBettingMoney;
            playerArray[playerIdx].playerBettingMoney = maxBet;
            playerArray[playerIdx].playerMoney -= maxBet;
            pot += maxBet;
        }
        UpdateUIText();
    }

    public void raise(int playerIdx)
    {
        roundBet += defaultBet;
        endOrder = playerIdx;

        playerArray[playerIdx].playerBettingMoney += roundBet;
        playerArray[playerIdx].playerMoney -= roundBet;
        pot += roundBet;
        maxBet = playerArray[playerIdx].playerBettingMoney;
        endOrder = playerIdx;
        UpdateUIText();
    }

    public void fold(int playerIdx)
    {
        /*
        ~~
        TODO : ШЎЗќРК potПЁ ЕћЖѓ КЏЕПЕЧЕЕЗЯ КЏАц
        ~~
        */


        if (20f + TestGameManager.Instance.playerArray[playerIdx].cheatFrequency < UnityEngine.Random.Range(0, 101))
        {
            TestGameManager.Instance.playerIsCheat[playerIdx] = true;
            call(playerIdx);
            return;
        }


        isFold[playerIdx] = true;
        TestGameManager.Instance.foldPlayerCnt++;

        

        CheckWinnerByFold();
        UpdateUIText();
    }
    #endregion

    #region win by fold

    private void CheckWinnerByFold()
    {
        if (TestGameManager.Instance.foldPlayerCnt == TestGameManager.Instance.IngamePlayerCnt - 1)
        {
            isBetOver = true;
        }
    }

    public List<int> DecideWinnerByFold(int playerIdx) //winner list ЙнШЏ
    {
        isBetOver = true;
        winner.Clear();
        winner.Add(playerIdx);
        winnerText[0].text = playerIdx.ToString();
        return winner;
    }

    #endregion

    #region afterBet

    public void ResetBet() //КЃЦУБн, ЦЬ Ею ЕЅРЬХЭ ИЎМТ
    {
        dealtCardCount = 0;
        endOrder = playerArray.Length;
        isBetOver = false;
        for (int i = 0; i < playerArray.Length; i++)
        {
            playerArray[i].playerBettingMoney = 0;
            isFold[i] = false;
        }
        roundBet = defaultBet;
        pot = 0;
        prize = 0;
    }

    public List<int> DecideWinner(int[] sum) //winner list ЙнШЏ
    {
        int max = 0;
        for (int i = 0; i < sum.Length; i++)
        {
            if (sum[i] > 21 || 21 - sum[i] > 21 - max || isFold[i] == true)
                continue;
            else if (21 - sum[i] < 21 - max)
            {
                max = sum[i];
                winner.Clear();
            }
            winner.Add(i);
        }
        for (int i = 0; i < winner.Count; i++)
            winnerText[i].text = winner[i].ToString();
        return winner;
    }

    public void CalculateResult(List<int> playerIdx) //winnerПЁАд prize РќДо, 
    {
        isBetOver = true;
        if (winner.Count != 0)
            prize = pot / winner.Count;
        for (; winner.Count > 0; winner.RemoveAt(0))
            playerArray[winner[0]].playerMoney += prize;
        UpdateUIText();
        for (int i = 0; i < playerArray.Length; i++)
        {
            if (eliminationCriteria > playerArray[i].playerMoney)
            {
                TestGameManager.Instance.EliminatePlayer(i, TestGameManager.NO_MONEY_ELIMINATED);
            }
        }
        TestGameManager.Instance.TriggerNextTurn();
    }

    #endregion
}
