using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

public class TopCardController : MonoBehaviour
{
    [SerializeField] private Transform topCard;
    private bool isDragging = false;
    private Vector3 mouseOffset;

    public event Action<bool> TopCardMoved;

    private float topCardTopY;
    private float topCardBottomY;

    private Vector3 origin_position; //нҒҙлҰӯн•ҳлҠ”мҲңк°„ к·ё м№ҙл“ңмқҳ кё°ліёмң„м№ҳлҘј мһЎмқҖлӢӨмқҢ, лӮҙк°Җ мқҙм ң к·ё мң„м№ҳм—җм„ң нҠ№м • к°’л§ҢнҒј мқҙлҸҷн•ҙм•јл§Ң мӢӨн–үлҗҳкІҢлҒ”
    [SerializeField] private AudioClip CardClickSound;
    private void Start()
    {
        SetPosition();
    }

    private void SetPosition()
    {
        // frontCardмқҳ BoxCollider2Dм—җм„ң мғҒлӢЁкіј н•ҳлӢЁ Y к°’мқ„ к°Җм ёмҳҙ
        BoxCollider2D collider = topCard.GetComponent<BoxCollider2D>();
        topCardTopY = collider.bounds.max.y;
        topCardBottomY = collider.bounds.min.y;
    }

    void OnMouseDown()
    {
        if (DialogManager.Instance.isDialogHighPriority || DialogManager.Instance.isDialogMiddlePriority)
            return;
        if (GameManager.Instance.gameState != GameManager.GameState.deal)
            return;
        if (!(GameManager.Instance.mousePointState == GameManager.MousePointState.normal))
            return;
        Vector2 mousePos = Camera.main.ScreenToWorldPoint(Input.mousePosition);
        origin_position = topCard.position;
        Collider2D collider = topCard.GetComponent<Collider2D>();


        AudioManager.GetOrCreate().PlayEffectSound(CardClickSound);
        if (mousePos.y >= topCardBottomY && mousePos.y <= topCardTopY)
        {
            isDragging = true;
            
            // л§Ҳмҡ°мҠӨ мң„м№ҳмҷҖ мҳӨлёҢм қнҠё мң„м№ҳ к°„мқҳ мҳӨн”„м…Ӣ кі„мӮ°
            Vector3 mousePosition = Input.mousePosition;
            mousePosition.z = Camera.main.WorldToScreenPoint(topCard.position).z;
            Vector3 worldPosition = Camera.main.ScreenToWorldPoint(mousePosition);
            mouseOffset = topCard.position - worldPosition;
        }
        else
        {
            isDragging = false;
        }
    }

    void OnMouseDrag()
    {
        if (isDragging)
        {
            // л§Ҳмҡ°мҠӨ мң„м№ҳлҘј мӣ”л“ң мўҢн‘ңлЎң ліҖнҷҳ
            Vector3 mousePosition = Input.mousePosition;
            mousePosition.z = Camera.main.WorldToScreenPoint(topCard.position).z;
            Vector3 worldPosition = Camera.main.ScreenToWorldPoint(mousePosition);

            // мғҲлЎңмҡҙ y мң„м№ҳ кі„мӮ° л°Ҹ м Ғмҡ©
            float newY = worldPosition.y + mouseOffset.y;

            if (newY < origin_position.y)
                newY = origin_position.y;
            // x, z мң„м№ҳ кі м •, y мң„м№ҳл§Ң ліҖкІҪ
            topCard.position = new Vector3(topCard.position.x, newY, topCard.position.z);
        }
    }

    void OnMouseUp()
    {
        if (isDragging)
        {
            if(Math.Abs(topCard.position.y - origin_position.y) > 0.2f)
            {
                isDragging = false;
                GameManager.Instance.NormalDeal();
                topCard.gameObject.SetActive(false); // frontCardлҘј л№„нҷңм„ұнҷ”
                DealingManager.Instance.TopSetImage();
                TopCardMoved?.Invoke(true); // мқҙлІӨнҠё нҳём¶ң
                Destroy(gameObject);
            }
            else
            {
                GameManager.Instance.IncreaseSuspicionByDragButDontDeal();
                topCard.gameObject.transform.position = origin_position;
            }
          
        }
    }
}
